version: '3'
services:
  database:
    container_name: minerva_db_postgres
    image: 'postgres:latest'
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:

