version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      -DATABASE_HOST: db
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/teste/
    env_file:
      - ./.env
    environment:
      -DATABASE_HOST: localhost
    expose:
      - 5432
    ports:
      - 5432:5432

volumes:
    postgres_data: